// frontend/src/components/TemplateTestView.jsx
import React, { useState, useRef, useEffect } from 'react';
import QuotaChart from './QuotaChart.jsx';

export default function TemplateTestView({ template }) {
  const [method, setMethod] = useState('GET');
  const [path, setPath] = useState('/');
  const [headers, setHeaders] = useState([]);
  const [body, setBody] = useState('');
  const [consoleLines, setConsoleLines] = useState([]);
  const [rateLimit, setRateLimit] = useState({});
  const [quotaUsed, setQuotaUsed] = useState(0);
  const [quotaTotal, setQuotaTotal] = useState(100);
  const consoleRef = useRef();

  useEffect(() => {
    // prepare auth header
    const h = [];
    if (template) {
      if (template.authMethod === 'API_TOKEN' || template.authMethod === 'BEARER')
        h.push({ key: 'Authorization', value: `Bearer ${template.authCredential}` });
      else if (template.authMethod === 'BASIC_AUTH')
        h.push({ key: 'Authorization', value: `Basic ${template.authCredential}` });
    }
    setHeaders(h);
  }, [template]);

  useEffect(() => {
    if (consoleRef.current) consoleRef.current.scrollTop = consoleRef.current.scrollHeight;
  }, [consoleLines]);

  const runTest = async () => {
    const base = template.apiUri || '';
    const p = path.startsWith('/') ? path : '/' + path;
    const url = base.replace(/\/$/, '') + p;
    setConsoleLines((l) => [...l, { type: 'req', text: `${method} ${url}` }]);
    const hdrs = { 'Content-Type': 'application/json' };
    headers.forEach((h) => {
      if (h.key) hdrs[h.key] = h.value;
    });
    const start = Date.now();
    try {
      const res = await fetch(url, {
        method,
        headers: hdrs,
        body: ['GET', 'DELETE'].includes(method) ? undefined : body || undefined,
      });
      const t = Date.now() - start;
      const txt = await res.text().catch(() => '<no body>');

      // Extract rate limit headers
      const rateLimitHeaders = {};
      const commonHeaders = [
        'x-ratelimit-limit',
        'x-ratelimit-remaining',
        'x-ratelimit-reset',
        'x-rate-limit-limit',
        'x-rate-limit-remaining',
        'x-rate-limit-reset',
        'ratelimit-limit',
        'ratelimit-remaining',
        'ratelimit-reset',
      ];
      commonHeaders.forEach((h) => {
        const value = res.headers.get(h);
        if (value) rateLimitHeaders[h] = value;
      });
      if (Object.keys(rateLimitHeaders).length > 0) {
        setRateLimit(rateLimitHeaders);
        // Parse remaining from common headers
        const remaining =
          res.headers.get('x-ratelimit-remaining') ||
          res.headers.get('x-rate-limit-remaining') ||
          res.headers.get('ratelimit-remaining');
        const limit =
          res.headers.get('x-ratelimit-limit') ||
          res.headers.get('x-rate-limit-limit') ||
          res.headers.get('ratelimit-limit');
        if (remaining && limit) {
          setQuotaUsed(Math.max(0, parseInt(limit) - parseInt(remaining)));
          setQuotaTotal(parseInt(limit));
        }
      }

      setConsoleLines((l) => [
        ...l,
        { type: 'res', text: `${res.status} ${res.statusText} — ${t}ms` },
        { type: 'res', text: txt.slice(0, 2000) },
      ]);
    } catch (err) {
      setConsoleLines((l) => [...l, { type: 'res', text: `ERROR: ${err.message}` }]);
    }
  };

  return (
    <div className="relative w-full">
      <div className="flex flex-row lg:flex-row bg-white gap-4 p-4 w-full">
        <div className="flex flex-col gap-4 flex-1">
          <p className="form-label">Request</p>
          <div className="flex gap-2 mb-3">
            <select
              value={method}
              onChange={(e) => setMethod(e.target.value)}
              className="form-select w-32"
            >
              <option>GET</option>
              <option>POST</option>
              <option>PUT</option>
              <option>DELETE</option>
              <option>PATCH</option>
            </select>
            <input
              value={path}
              onChange={(e) => setPath(e.target.value)}
              className="form-input flex-1"
              placeholder="/"
            />
          </div>

          <div className="mb-3">
            <p className="form-label mb-2">Headers</p>
            {headers.map((h, idx) => (
              <div key={idx} className="flex gap-2 mb-2">
                <input
                  value={h.key}
                  onChange={(e) => {
                    const copy = [...headers];
                    copy[idx].key = e.target.value;
                    setHeaders(copy);
                  }}
                  className="form-input w-1-3"
                  placeholder="Key"
                />
                <input
                  value={h.value}
                  onChange={(e) => {
                    const copy = [...headers];
                    copy[idx].value = e.target.value;
                    setHeaders(copy);
                  }}
                  className="form-input flex-1"
                  placeholder="Value"
                />
              </div>
            ))}
          </div>

          <div className="mb-3">
            <p className="form-label mb-2">Body (JSON)</p>
            <textarea
              value={body}
              onChange={(e) => setBody(e.target.value)}
              rows={6}
              className="form-textarea"
              placeholder="{}"
            />
          </div>

          <div className="flex gap-2 justify-end">
            <button onClick={runTest} className="btn-primary">
              Run Test
            </button>
          </div>
        </div>

        <div className='flex flex-row lg:flex-row gap-4 flex-1'>
          <div className="flex flex-col bg-white shadow rounded-lg p-4 flex-1">
            <p className="form-label mb-3">Console</p>
            <div
              className="console-root border rounded p-3 h-full overflow-y-auto bg-gray-900 text-gray-100"
              ref={consoleRef}
            >
              {consoleLines.map((ln, i) => (
                <div
                  key={i}
                  className={`console-line ${ln.type === 'req' ? 'text-blue-400' : 'text-green-400'} font-mono text-xs mb-1`}
                >
                  {ln.type === 'req' ? '→ ' : '← '}
                  {ln.text}
                </div>
              ))}
            </div>
          </div>

          {quotaTotal > 0 && (
            <div className="flex-1">
              <QuotaChart rateLimit={rateLimit} quotaUsed={quotaUsed} quotaTotal={quotaTotal} />
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// frontend/src/components/TemplateTestView.vue
<template>
  <div class="space-y-4">
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
      <!-- Left: Request builder -->
      <div class="space-y-3">
        <div class="flex gap-2">
          <select v-model="method" class="w-32 p-2 border rounded">
            <option>GET</option>
            <option>POST</option>
            <option>PUT</option>
            <option>DELETE</option>
            <option>PATCH</option>
          </select>
          <input v-model="path" class="flex-1 p-2 border rounded" />
        </div>

        <div>
          <p class="text-sm muted mb-1">Headers</p>
          <div v-for="(h, idx) in headers" :key="idx" class="flex gap-2 mb-2">
            <input v-model="h.key" class="w-1/3 p-2 border rounded" placeholder="Header" />
            <input v-model="h.value" class="flex-1 p-2 border rounded" placeholder="Value" />
          </div>
        </div>

        <div>
          <p class="text-sm muted mb-1">Body (JSON)</p>
          <textarea v-model="body" rows="6" class="w-full p-2 border rounded font-mono"></textarea>
        </div>

        <div class="flex gap-2 justify-end">
          <button @click="runTest" class="btn-primary px-4 py-2 rounded">Run</button>
          <button @click="clearConsole" class="btn-secondary px-4 py-2 rounded">Clear</button>
        </div>
      </div>

      <!-- Middle: Charts / stats (placeholders) -->
      <div class="lg:col-span-1 space-y-4">
        <div class="card-root">
          <h4 class="font-semibold mb-2">Quick Stats</h4>
          <p class="text-sm muted">Last status: <strong>{{ lastStatus || '—' }}</strong></p>
          <p class="text-sm muted">Avg latency: <strong>{{ avgLatencyDisplay }}</strong></p>
        </div>

        <div class="card-root">
          <h4 class="font-semibold mb-2">Capacity / Usage</h4>
          <p class="text-sm muted">(Charts to be implemented)</p>
        </div>
      </div>

      <!-- Right: Console -->
      <div class="lg:col-span-1">
        <div>
          <p class="text-sm muted mb-2">Console</p>
          <div class="console-root" ref="consoleRef">
            <div v-for="(line, i) in consoleLines" :key="i" class="console-line">
              <div v-if="line.type === 'request'" class="console-request">→ {{ line.text }}</div>
              <div v-else class="console-response">← {{ line.text }}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted, nextTick } from 'vue';

const props = defineProps({
  template: { type: Object, required: true }
});

const method = ref('GET');
const path = ref('/');
const headers = ref([]);
const body = ref('');
const consoleLines = ref([]);
const lastStatus = ref(null);
const latencies = ref([]);
const consoleRef = ref(null);

onMounted(() => {
  // populate auth header based on template
  const t = props.template;
  headers.value = [];
  if (t.authMethod === 'API_TOKEN' || t.authMethod === 'BEARER') {
    headers.value.push({ key: 'Authorization', value: `Bearer ${t.authCredential}` });
  } else if (t.authMethod === 'BASIC_AUTH') {
    headers.value.push({ key: 'Authorization', value: `Basic ${t.authCredential}` });
  }
});

watch(consoleLines, () => {
  // auto-scroll
  nextTick(() => {
    if (consoleRef.value) {
      consoleRef.value.scrollTop = consoleRef.value.scrollHeight;
    }
  });
});

const formatUrl = () => {
  let base = props.template.apiUri || '';
  if (base.endsWith('/')) base = base.slice(0, -1);
  let p = path.value || '';
  if (!p.startsWith('/')) p = '/' + p;
  return base + p;
};

const runTest = async () => {
  const url = formatUrl();
  const hdrs = {};
  for (const h of headers.value) {
    if (h.key && h.value) hdrs[h.key] = h.value;
  }

  consoleLines.value.push({ type: 'request', text: `${method.value} ${url}` });
  const start = Date.now();
  try {
    const res = await fetch(url, {
      method: method.value,
      headers: { 'Content-Type': 'application/json', ...hdrs },
      body: ['GET','DELETE'].includes(method.value) ? undefined : (body.value || undefined),
    });

    const time = Date.now() - start;
    latencies.value.push(time);
    lastStatus.value = `${res.status} ${res.statusText}`;

    let text;
    try { text = await res.text(); } catch(e){ text = '<no body>'; }

    consoleLines.value.push({ type: 'response', text: `${res.status} ${res.statusText} — ${time}ms` });
    // show snippet
    consoleLines.value.push({ type: 'response', text: text.slice(0, 2000) });
  } catch (err) {
    const time = Date.now() - start;
    latencies.value.push(time);
    consoleLines.value.push({ type: 'response', text: `ERROR: ${err.message}` });
  }
};

const clearConsole = () => { consoleLines.value = []; };

const avgLatencyDisplay = computed(() => {
  if (latencies.value.length === 0) return '—';
  const sum = latencies.value.reduce((a,b)=>a+b,0);
  return Math.round(sum/latencies.value.length) + ' ms';
});
</script>

<style scoped>
.card-root{padding:1rem}
</style>
